name: tfpcbpggsz 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - tensorflow
  - keras
  - tf-keras
  - tensorflow-probability
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - uproot
  - sympy
  - pyyaml
