import numpy as np

VARIABLES_RUN1 = {
    "Bu_ID": np.float64,
    "Bu_M": np.float64,
    "Bu_constD0KSPV_M": np.float64,
    "Bu_constD0PV_M"  : np.float64,
    "Bu_constKSPV_M"  : np.float64,
    # "eventNumber": np.float64,
    "Bu_constD0KSPV_chi2": np.float64,
    "Bu_constD0KSPV_nDOF": np.float64,
    "Bu_constD0PV_chi2"  : np.float64,
    "Bu_constD0PV_nDOF"  : np.float64,
    "Bu_constKSPV_chi2"  : np.float64,
    "Bu_constKSPV_nDOF"  : np.float64,
    "h1_ID": np.float64,
    "Ks_PE": np.float64,
    "Ks_PX": np.float64,
    "Ks_PY": np.float64,
    "Ks_PZ": np.float64,
    "h1_PE": np.float64,
    "h1_PX": np.float64,
    "h1_PY": np.float64,
    "h1_PZ": np.float64,
    "h2_ID": np.float64,
    "h2_PE": np.float64,
    "h2_PX": np.float64,
    "h2_PY": np.float64,
    "h2_PZ": np.float64,
    "Ksh2_IPCHI2_OWNPV": np.float64,
    "Ksh1_IPCHI2_OWNPV": np.float64,
    "h2_IPCHI2_OWNPV"  : np.float64,
    "h1_IPCHI2_OWNPV"  : np.float64,
    "D0_ENDVERTEX_Z"   : np.float64,
    "Bu_ENDVERTEX_Z"   : np.float64,
    "D0_ENDVERTEX_ZERR": np.float64,
    "Bu_ENDVERTEX_ZERR": np.float64,
    "Bu_constD0KSPV_status": np.float64,
    "Bu_constD0PV_status": np.float64,
    "Bu_constKSPV_status": np.float64,
    "Ks_M": np.float64,
    "h2_ID": np.float64,
    "h1_hasRich": np.float64,
    "h2_hasRich": np.float64,
    "Bu_M": np.float64,
    "h1_MC12TuneV2_ProbNNk": np.float64,
    "h2_MC12TuneV2_ProbNNk": np.float64,
    "h1_MC12TuneV2_ProbNNpi": np.float64,
    "h2_MC12TuneV2_ProbNNpi": np.float64,    
    "Bach_MC12TuneV2_ProbNNe": np.float64, 
    "Bach_MC12TuneV2_ProbNNmu": np.float64,  
    "Bach_MC12TuneV2_ProbNNpi": np.float64,  
    "Bach_MC12TuneV2_ProbNNk": np.float64, 
    "Bach_MC12TuneV2_ProbNNghost": np.float64,
    "Ksh1_MC12TuneV2_ProbNNe": np.float64, 
    "Ksh1_MC12TuneV2_ProbNNmu": np.float64,  
    "Ksh1_MC12TuneV2_ProbNNpi": np.float64,  
    "Ksh1_MC12TuneV2_ProbNNk": np.float64, 
    "Ksh1_MC12TuneV2_ProbNNghost": np.float64,
    "Ksh2_MC12TuneV2_ProbNNe": np.float64, 
    "Ksh2_MC12TuneV2_ProbNNmu": np.float64,  
    "Ksh2_MC12TuneV2_ProbNNpi": np.float64,  
    "Ksh2_MC12TuneV2_ProbNNk": np.float64, 
    "Ksh2_MC12TuneV2_ProbNNghost": np.float64,
    "h1_MC12TuneV4_ProbNNk": np.float64,
    "h2_MC12TuneV4_ProbNNk": np.float64,
    "h1_MC12TuneV4_ProbNNpi": np.float64,
    "h2_MC12TuneV4_ProbNNpi": np.float64,    
    "Bach_MC12TuneV4_ProbNNe": np.float64, 
    "Bach_MC12TuneV4_ProbNNmu": np.float64,  
    "Bach_MC12TuneV4_ProbNNpi": np.float64,  
    "Bach_MC12TuneV4_ProbNNk": np.float64, 
    "Bach_MC12TuneV4_ProbNNghost": np.float64,
    "Ksh1_MC12TuneV4_ProbNNe": np.float64, 
    "Ksh1_MC12TuneV4_ProbNNmu": np.float64,  
    "Ksh1_MC12TuneV4_ProbNNpi": np.float64,  
    "Ksh1_MC12TuneV4_ProbNNk": np.float64, 
    "Ksh1_MC12TuneV4_ProbNNghost": np.float64,
    "Ksh2_MC12TuneV4_ProbNNe": np.float64, 
    "Ksh2_MC12TuneV4_ProbNNmu": np.float64,  
    "Ksh2_MC12TuneV4_ProbNNpi": np.float64,  
    "Ksh2_MC12TuneV4_ProbNNk": np.float64, 
    "Ksh2_MC12TuneV4_ProbNNghost": np.float64,
    "Bach_IPCHI2_OWNPV":np.float64,
    "D0_IPCHI2_OWNPV":np.float64,
    "Bu_IPCHI2_OWNPV":np.float64,
    "Bu_FDCHI2_OWNPV":np.float64,
    "Bu_P":np.float64,
    "Bu_PT":np.float64,
    "D0_P":np.float64,
    "D0_PT":np.float64,
    "Bach_PT":np.float64,
    "Bach_P":np.float64,
    "Bu_RHO_BPV":np.float64,
    "D0_RHO_BPV":np.float64,
    "D0_VTXCHI2DOF":np.float64,
    "Ks_VTXCHI2DOF":np.float64,
    "Bu_VTXCHI2DOF":np.float64,
    "Bu_DIRA_BPV":np.float64,
    "D0_DIRA_BPV":np.float64,
    "Ks_DIRA_BPV":np.float64,
    "Bu_MAXDOCA":np.float64,
    "D0_MAXDOCA":np.float64,
    "Bu_PTASY_1.5":np.float64,
    "Bu_L0Global_TIS":np.int32,
    "Bu_L0HadronDecision_TOS" :np.int32,
    "Bu_Hlt1TrackAllL0Decision_TOS"   : np.int32,
    "Bu_Hlt2Topo2BodyBBDTDecision_TOS": np.int32,
    "Bu_Hlt2Topo3BodyBBDTDecision_TOS": np.int32,
    "Bu_Hlt2Topo4BodyBBDTDecision_TOS": np.int32,
    "Bu_constD0PV_KS0_M": np.float64,
    "Bu_constKSPV_D0_M" : np.float64,
    'Bu_constD0KSPV_swapBachToPi_M':      np.float64,
    'Bu_constD0KSPV_swapBachToPi_status': np.float64,
    'Bu_constD0KSPV_swapBachToK_M':      np.float64,
    'Bu_constD0KSPV_swapBachToK_status': np.float64,
    "Bach_PIDe"  : np.float64, 
    "Bach_isMuon": np.float64, 
    "h1_PIDe"  : np.float64, 
    "h1_isMuon": np.float64, 
    "h2_PIDe"  : np.float64, 
    "h2_isMuon": np.float64, 
    "h1_PIDK": np.float64,
    "h2_PIDK": np.float64,
    "eventNumber": np.float64,
    "runNumber": np.float64,
    "Bach_PIDK"  : np.float64, 
    "Ks_FDCHI2_ORIVX": np.float64,
    "Bach_hasRich": np.float64,
}

TRUTH_VARIABLES_RUN1 = {
    "Ks_TRUEP_E": np.float64,
    "Ks_TRUEP_X": np.float64,
    "Ks_TRUEP_Y": np.float64,
    "Ks_TRUEP_Z": np.float64,
    "h1_TRUEP_E": np.float64,
    "h1_TRUEP_X": np.float64,
    "h1_TRUEP_Y": np.float64,
    "h1_TRUEP_Z": np.float64,
    "h2_TRUEP_E": np.float64,
    "h2_TRUEP_X": np.float64,
    "h2_TRUEP_Y": np.float64,
    "h2_TRUEP_Z": np.float64,
    "D0_TRUEID": np.int32,              
    "D0_MC_MOTHER_ID": np.int32,              
    "Bach_MC_MOTHER_ID": np.int32,      
    "Ks_TRUEID": np.int32,              
    "Ks_MC_MOTHER_ID": np.int32,        
    "Ks_MC_GD_MOTHER_ID": np.int32,     
    "h1_MC_MOTHER_ID": np.int32,        
    "h1_MC_GD_MOTHER_ID": np.int32,     
    "h2_MC_MOTHER_ID": np.int32,        
    "h2_MC_GD_MOTHER_ID": np.int32,     
    "Ksh1_TRUEID": np.int32,            
    "Ksh1_MC_MOTHER_ID": np.int32,      
    "Ksh1_MC_GD_MOTHER_ID": np.int32,   
    "Ksh1_MC_GD_GD_MOTHER_ID": np.int32,
    "Ksh2_TRUEID": np.int32,            
    "Ksh2_MC_MOTHER_ID": np.int32,      
    "Ksh2_MC_GD_MOTHER_ID": np.int32,   
    "Ksh2_MC_GD_GD_MOTHER_ID": np.int32,
    "Bach_TRUEID": np.int32,
    "Bach_TRUEID": np.int32,
    "h1_TRUEID": np.int32,
    "h2_TRUEID": np.int32,
    "h1_TRUEID": np.int32,
    "h2_TRUEID": np.int32,
}

NEW_VARIABLES_RUN1 = {
    "min_Ksh1h2_IPCHI2_OWNPV": np.float64,
    "max_Ksh1h2_IPCHI2_OWNPV": np.float64,
    "min_h1h2_IPCHI2_OWNPV"  : np.float64,
    "max_h1h2_IPCHI2_OWNPV"  : np.float64,
    "BD_ZSIG"                : np.float64,
    "Bu_constD0KSPV_CHI2NDOF": np.float64,
    "Bu_constD0PV_CHI2NDOF"  : np.float64,
    "Bu_constKSPV_CHI2NDOF"  : np.float64,
    "m_Kspip" : np.float64,
    "m_Kspim" : np.float64,
    "m_pippim": np.float64,
    # "zp"      : np.float64,
    # "zm"      : np.float64,
    "zp_p"    : np.float64,
    "zm_pp"   : np.float64,
    "log_min_h1h2_IPCHI2_OWNPV":np.float64,
    "log_max_h1h2_IPCHI2_OWNPV":np.float64,
    "log_Bach_IPCHI2_OWNPV":np.float64,
    "log_min_Ksh1h2_IPCHI2_OWNPV":np.float64,
    "log_max_Ksh1h2_IPCHI2_OWNPV":np.float64,
    "log_D0_IPCHI2_OWNPV":np.float64,
    "log_Bu_IPCHI2_OWNPV":np.float64,
    "log_Bu_FDCHI2_OWNPV":np.float64,
    "log_Bu_P":np.float64,
    "log_Bu_PT":np.float64,
    "log_D0_P":np.float64,
    "log_D0_PT":np.float64,
    "log_Bach_PT":np.float64,
    "log_Bach_P":np.float64,
    "log_Bu_RHO_BPV":np.float64,
    "log_D0_RHO_BPV":np.float64,
    "log_D0_VTXCHI2DOF":np.float64,
    "log_Ks_VTXCHI2DOF":np.float64,
    "log_Bu_VTXCHI2DOF":np.float64,
    "log10_1_minus_Bu_DIRA_BPV":np.float64,
    "log10_1_minus_D0_DIRA_BPV":np.float64,
    "log10_1_minus_Ks_DIRA_BPV":np.float64,
    "log_Bu_constD0KSPV_CHI2NDOF":np.float64,
    "Bu_PTASY_1_5":np.float64,
    "is_in_D_PhaseSpace":np.int32,
}
NEW_TRUTH_VARIABLES_RUN1 = {
    "m_Kspip_True"   : np.float64,
    "m_Kspim_True"   : np.float64,
    "m_pippim_True"  : np.float64,
    # "zp_True"  : np.float64, 
    # "zm_True"  : np.float64, 
    "zp_p_True": np.float64, 
    "zm_pp_True": np.float64,
}


############### RUN2
VARIABLES_RUN2 = {
    "Bu_ID": np.float64,
    "Bu_M": np.float64,
    "Bu_constD0KSPV_M": np.float64,
    "Bu_constD0PV_M"  : np.float64,
    "Bu_constKSPV_M"  : np.float64,
    # "eventNumber": np.float64,
    "Bu_constD0KSPV_chi2": np.float64,
    "Bu_constD0KSPV_nDOF": np.float64,
    "Bu_constD0PV_chi2"  : np.float64,
    "Bu_constD0PV_nDOF"  : np.float64,
    "Bu_constKSPV_chi2"  : np.float64,
    "Bu_constKSPV_nDOF"  : np.float64,
    "h1_ID": np.float64,
    "Ks_PE": np.float64,
    "Ks_PX": np.float64,
    "Ks_PY": np.float64,
    "Ks_PZ": np.float64,
    "h1_PE": np.float64,
    "h1_PX": np.float64,
    "h1_PY": np.float64,
    "h1_PZ": np.float64,
    "h2_ID": np.float64,
    "h2_PE": np.float64,
    "h2_PX": np.float64,
    "h2_PY": np.float64,
    "h2_PZ": np.float64,
    "Ksh2_IPCHI2_OWNPV": np.float64,
    "Ksh1_IPCHI2_OWNPV": np.float64,
    "h2_IPCHI2_OWNPV"  : np.float64,
    "h1_IPCHI2_OWNPV"  : np.float64,
    "D0_ENDVERTEX_Z"   : np.float64,
    "Bu_ENDVERTEX_Z"   : np.float64,
    "D0_ENDVERTEX_ZERR": np.float64,
    "Bu_ENDVERTEX_ZERR": np.float64,
    "Bu_constD0KSPV_status": np.float64,
    "Bu_constD0PV_status": np.float64,
    "Bu_constKSPV_status": np.float64,
    "Ks_M": np.float64,
    "h1_MC15TuneV1_ProbNNk": np.float64,
    "h2_MC15TuneV1_ProbNNk": np.float64,
    "h1_MC15TuneV1_ProbNNpi": np.float64,
    "h2_MC15TuneV1_ProbNNpi": np.float64,    
    "h2_ID": np.float64,
    "h1_hasRich": np.float64,
    "h2_hasRich": np.float64,
    "Bu_M": np.float64,
    "Bach_MC15TuneV1_ProbNNe": np.float64, 
    "Bach_MC15TuneV1_ProbNNmu": np.float64,  
    "Bach_MC15TuneV1_ProbNNpi": np.float64,  
    "Bach_MC15TuneV1_ProbNNk": np.float64, 
    "Bach_MC15TuneV1_ProbNNghost": np.float64,
    "Ksh1_MC15TuneV1_ProbNNe": np.float64, 
    "Ksh1_MC15TuneV1_ProbNNmu": np.float64,  
    "Ksh1_MC15TuneV1_ProbNNpi": np.float64,  
    "Ksh1_MC15TuneV1_ProbNNk": np.float64, 
    "Ksh1_MC15TuneV1_ProbNNghost": np.float64,
    "Ksh2_MC15TuneV1_ProbNNe": np.float64, 
    "Ksh2_MC15TuneV1_ProbNNmu": np.float64,  
    "Ksh2_MC15TuneV1_ProbNNpi": np.float64,  
    "Ksh2_MC15TuneV1_ProbNNk": np.float64, 
    "Ksh2_MC15TuneV1_ProbNNghost": np.float64,
    "Bach_IPCHI2_OWNPV":np.float64,
    "D0_IPCHI2_OWNPV":np.float64,
    "Bu_IPCHI2_OWNPV":np.float64,
    "Bu_FDCHI2_OWNPV":np.float64,
    "Bu_P":np.float64,
    "Bu_PT":np.float64,
    "D0_P":np.float64,
    "D0_PT":np.float64,
    "Bach_PT":np.float64,
    "Bach_P":np.float64,
    "Bu_RHO_BPV":np.float64,
    "D0_RHO_BPV":np.float64,
    "D0_VTXCHI2DOF":np.float64,
    "Ks_VTXCHI2DOF":np.float64,
    "Bu_VTXCHI2DOF":np.float64,
    "Bu_DIRA_BPV":np.float64,
    "D0_DIRA_BPV":np.float64,
    "Ks_DIRA_BPV":np.float64,
    "Bu_MAXDOCA":np.float64,
    "D0_MAXDOCA":np.float64,
    "Bu_PTASY_1.5":np.float64,
    "Bu_L0Global_TIS":np.int32,
    "Bu_L0HadronDecision_TOS" :np.int32,
    "Bu_Hlt1TrackMVADecision_TOS"   : np.int32,
    "Bu_Hlt1TwoTrackMVADecision_TOS": np.int32,
    "Bu_Hlt2Topo2BodyDecision_TOS"  : np.int32,
    "Bu_Hlt2Topo3BodyDecision_TOS": np.int32,
    "Bu_Hlt2Topo4BodyDecision_TOS": np.int32,
    "Bu_constD0PV_KS0_M": np.float64,
    "Bu_constKSPV_D0_M" : np.float64, 
    'Bu_constD0KSPV_swapBachToPi_M':      np.float64,
    'Bu_constD0KSPV_swapBachToPi_status': np.float64,
    'Bu_constD0KSPV_swapBachToK_M':      np.float64,
    'Bu_constD0KSPV_swapBachToK_status': np.float64,
    "Bach_PIDe"  : np.float64, 
    "Bach_isMuon": np.float64, 
    "h1_PIDe"  : np.float64, 
    "h1_isMuon": np.float64, 
    "h2_PIDe"  : np.float64, 
    "h2_isMuon": np.float64, 
    "h1_PIDK": np.float64,
    "h2_PIDK": np.float64,
    "eventNumber": np.float64,
    "runNumber": np.float64,
    "Bach_PIDK"  : np.float64, 
    "Ks_FDCHI2_ORIVX": np.float64,
    "Bach_hasRich": np.float64,
}

TRUTH_VARIABLES_RUN2 = {
    "Ks_TRUEP_E": np.float64,
    "Ks_TRUEP_X": np.float64,
    "Ks_TRUEP_Y": np.float64,
    "Ks_TRUEP_Z": np.float64,
    "h1_TRUEP_E": np.float64,
    "h1_TRUEP_X": np.float64,
    "h1_TRUEP_Y": np.float64,
    "h1_TRUEP_Z": np.float64,
    "h2_TRUEP_E": np.float64,
    "h2_TRUEP_X": np.float64,
    "h2_TRUEP_Y": np.float64,
    "h2_TRUEP_Z": np.float64,
    "D0_TRUEID": np.int32,              
    "D0_MC_MOTHER_ID": np.int32,              
    "Bach_MC_MOTHER_ID": np.int32,      
    "Ks_TRUEID": np.int32,              
    "Ks_MC_MOTHER_ID": np.int32,        
    "Ks_MC_GD_MOTHER_ID": np.int32,     
    "h1_MC_MOTHER_ID": np.int32,        
    "h1_MC_GD_MOTHER_ID": np.int32,     
    "h2_MC_MOTHER_ID": np.int32,        
    "h2_MC_GD_MOTHER_ID": np.int32,     
    "Ksh1_TRUEID": np.int32,            
    "Ksh1_MC_MOTHER_ID": np.int32,      
    "Ksh1_MC_GD_MOTHER_ID": np.int32,   
    "Ksh1_MC_GD_GD_MOTHER_ID": np.int32,
    "Ksh2_TRUEID": np.int32,            
    "Ksh2_MC_MOTHER_ID": np.int32,      
    "Ksh2_MC_GD_MOTHER_ID": np.int32,   
    "Ksh2_MC_GD_GD_MOTHER_ID": np.int32,
    "Bach_TRUEID": np.int32,
    "Bach_TRUEID": np.int32,
    "h1_TRUEID": np.int32,
    "h2_TRUEID": np.int32,
    "h1_TRUEID": np.int32,
    "h2_TRUEID": np.int32,
}



NEW_VARIABLES_RUN2 = {
    "min_Ksh1h2_IPCHI2_OWNPV": np.float64,
    "max_Ksh1h2_IPCHI2_OWNPV": np.float64,
    "min_h1h2_IPCHI2_OWNPV"  : np.float64,
    "max_h1h2_IPCHI2_OWNPV"  : np.float64,
    "BD_ZSIG"                : np.float64,
    "Bu_constD0KSPV_CHI2NDOF": np.float64,
    "Bu_constD0PV_CHI2NDOF"  : np.float64,
    "Bu_constKSPV_CHI2NDOF"  : np.float64,
    "m_Kspip" : np.float64,
    "m_Kspim" : np.float64,
    "m_pippim": np.float64,
    # "zp"      : np.float64,
    # "zm"      : np.float64,
    "zp_p"    : np.float64,
    "zm_pp"   : np.float64,
    "log_min_h1h2_IPCHI2_OWNPV":np.float64,
    "log_max_h1h2_IPCHI2_OWNPV":np.float64,
    "log_Bach_IPCHI2_OWNPV":np.float64,
    "log_min_Ksh1h2_IPCHI2_OWNPV":np.float64,
    "log_max_Ksh1h2_IPCHI2_OWNPV":np.float64,
    "log_D0_IPCHI2_OWNPV":np.float64,
    "log_Bu_IPCHI2_OWNPV":np.float64,
    "log_Bu_FDCHI2_OWNPV":np.float64,
    "log_Bu_P":np.float64,
    "log_Bu_PT":np.float64,
    "log_D0_P":np.float64,
    "log_D0_PT":np.float64,
    "log_Bach_PT":np.float64,
    "log_Bach_P":np.float64,
    "log_Bu_RHO_BPV":np.float64,
    "log_D0_RHO_BPV":np.float64,
    "log_D0_VTXCHI2DOF":np.float64,
    "log_Ks_VTXCHI2DOF":np.float64,
    "log_Bu_VTXCHI2DOF":np.float64,
    "log10_1_minus_Bu_DIRA_BPV":np.float64,
    "log10_1_minus_D0_DIRA_BPV":np.float64,
    "log10_1_minus_Ks_DIRA_BPV":np.float64,
    "log_Bu_constD0KSPV_CHI2NDOF":np.float64,
    "Bu_PTASY_1_5":np.float64,
    "is_in_D_PhaseSpace":np.int32,
}

NEW_TRUTH_VARIABLES_RUN2 = {
    "m_Kspip_True"   : np.float64,
    "m_Kspim_True"   : np.float64,
    "m_pippim_True"  : np.float64,
    # "zp_True"  : np.float64, 
    # "zm_True"  : np.float64, 
    "zp_p_True": np.float64, 
    "zm_pp_True": np.float64,
}


VARIABLES = {
    "YRUN1": VARIABLES_RUN1,
    "YRUN2": VARIABLES_RUN2,
}

TRUTH_VARIABLES = {
    "YRUN1": TRUTH_VARIABLES_RUN1,
    "YRUN2": TRUTH_VARIABLES_RUN2,
}

NEW_VARIABLES = {
    "YRUN1": NEW_VARIABLES_RUN1,
    "YRUN2": NEW_VARIABLES_RUN2,
}

NEW_TRUTH_VARIABLES = {
    "YRUN1": NEW_TRUTH_VARIABLES_RUN1,
    "YRUN2": NEW_TRUTH_VARIABLES_RUN2,
}

VARIABLES_BACH_PROBNN = {
    "YRUN1" : {
        "CB2DK_D2KSPIPI_DD"  : ["Bach_MC12TuneV2_ProbNNk","Bach_MC12TuneV2_ProbNNpi"],
        "CB2DPI_D2KSPIPI_DD" : ["Bach_MC12TuneV2_ProbNNpi","Bach_MC12TuneV2_ProbNNk"],
        "CB2DK_D2KSPIPI_LL"  : ["Bach_MC12TuneV2_ProbNNk","Bach_MC12TuneV2_ProbNNpi"],
        "CB2DPI_D2KSPIPI_LL" : ["Bach_MC12TuneV2_ProbNNpi","Bach_MC12TuneV2_ProbNNk"],
        "CB2DK_D2KSKK_DD"    : ["Bach_MC12TuneV2_ProbNNk","Bach_MC12TuneV2_ProbNNpi"],
        "CB2DPI_D2KSKK_DD"   : ["Bach_MC12TuneV2_ProbNNpi","Bach_MC12TuneV2_ProbNNk"],
        "CB2DK_D2KSKK_LL"    : ["Bach_MC12TuneV2_ProbNNk","Bach_MC12TuneV2_ProbNNpi"],
        "CB2DPI_D2KSKK_LL"   : ["Bach_MC12TuneV2_ProbNNpi","Bach_MC12TuneV2_ProbNNk"],
    },
    "YRUN2" : {
        "CB2DK_D2KSPIPI_DD"  : ["Bach_MC15TuneV1_ProbNNk","Bach_MC15TuneV1_ProbNNpi"],
        "CB2DPI_D2KSPIPI_DD" : ["Bach_MC15TuneV1_ProbNNpi","Bach_MC15TuneV1_ProbNNk"],
        "CB2DK_D2KSPIPI_LL"  : ["Bach_MC15TuneV1_ProbNNk","Bach_MC15TuneV1_ProbNNpi"],
        "CB2DPI_D2KSPIPI_LL" : ["Bach_MC15TuneV1_ProbNNpi","Bach_MC15TuneV1_ProbNNk"],
        "CB2DK_D2KSKK_DD"    : ["Bach_MC15TuneV1_ProbNNk","Bach_MC15TuneV1_ProbNNpi"],
        "CB2DPI_D2KSKK_DD"   : ["Bach_MC15TuneV1_ProbNNpi","Bach_MC15TuneV1_ProbNNk"],
        "CB2DK_D2KSKK_LL"    : ["Bach_MC15TuneV1_ProbNNk","Bach_MC15TuneV1_ProbNNpi"],
        "CB2DPI_D2KSKK_LL"   : ["Bach_MC15TuneV1_ProbNNpi","Bach_MC15TuneV1_ProbNNk"],
    },
}
VARIABLES_BACH_PROBNN_COMB = {
    "YRUN1" : {
        "CB2DK_D2KSPIPI_DD" : "Bach_MC12TuneV2_ProbNNk*(1-Bach_MC12TuneV2_ProbNNpi)",
        "CB2DPI_D2KSPIPI_DD": "Bach_MC12TuneV2_ProbNNpi*(1-Bach_MC12TuneV2_ProbNNk)",
        "CB2DK_D2KSPIPI_LL"  : "Bach_MC12TuneV2_ProbNNk*(1-Bach_MC12TuneV2_ProbNNpi)",
        "CB2DPI_D2KSPIPI_LL" : "Bach_MC12TuneV2_ProbNNpi*(1-Bach_MC12TuneV2_ProbNNk)",
        "CB2DK_D2KSKK_DD"    : "Bach_MC12TuneV2_ProbNNk*(1-Bach_MC12TuneV2_ProbNNpi)",
        "CB2DPI_D2KSKK_DD"   : "Bach_MC12TuneV2_ProbNNpi*(1-Bach_MC12TuneV2_ProbNNk)",
        "CB2DK_D2KSKK_LL"    : "Bach_MC12TuneV2_ProbNNk*(1-Bach_MC12TuneV2_ProbNNpi)",
        "CB2DPI_D2KSKK_LL"   : "Bach_MC12TuneV2_ProbNNpi*(1-Bach_MC12TuneV2_ProbNNk)",
    },
    "YRUN2" : {
        "CB2DK_D2KSPIPI_DD" : "Bach_MC15TuneV1_ProbNNk*(1-Bach_MC15TuneV1_ProbNNpi)",
        "CB2DPI_D2KSPIPI_DD": "Bach_MC15TuneV1_ProbNNpi*(1-Bach_MC15TuneV1_ProbNNk)",
        "CB2DK_D2KSPIPI_LL" : "Bach_MC15TuneV1_ProbNNk*(1-Bach_MC15TuneV1_ProbNNpi)",
        "CB2DPI_D2KSPIPI_LL": "Bach_MC15TuneV1_ProbNNpi*(1-Bach_MC15TuneV1_ProbNNk)",
        "CB2DK_D2KSKK_DD"   : "Bach_MC15TuneV1_ProbNNk*(1-Bach_MC15TuneV1_ProbNNpi)",
        "CB2DPI_D2KSKK_DD"  : "Bach_MC15TuneV1_ProbNNpi*(1-Bach_MC15TuneV1_ProbNNk)",
        "CB2DK_D2KSKK_LL"   : "Bach_MC15TuneV1_ProbNNk*(1-Bach_MC15TuneV1_ProbNNpi)",
        "CB2DPI_D2KSKK_LL"  : "Bach_MC15TuneV1_ProbNNpi*(1-Bach_MC15TuneV1_ProbNNk)",
    },
}
